import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-geist)'],
        mono: ['var(--font-geist-mono)'],
      },
      screens: {
        'xs': '475px',
        'toast-mobile': '600px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        // BITS Pilani Dubai Campus Brand Colors
        'bits-royal-blue': {
          50: '#e6f0ff',
          100: '#b3d1ff',
          200: '#80b2ff',
          300: '#4d93ff',
          400: '#1a74ff',
          500: '#002E6E',
          600: '#00255a',
          700: '#001c46',
          800: '#001332',
          900: '#000a1e',
          950: '#000714',
        },
        'bits-golden-yellow': {
          50: '#fff8e6',
          100: '#ffedb3',
          200: '#ffe280',
          300: '#ffd74d',
          400: '#ffcc1a',
          500: '#F2B300',
          600: '#c28f00',
          700: '#926b00',
          800: '#624700',
          900: '#322300',
          950: '#1a1200',
        },
        'bits-bright-red': {
          50: '#ffe6e8',
          100: '#ffb3b8',
          200: '#ff8088',
          300: '#ff4d58',
          400: '#ff1a28',
          500: '#C1121F',
          600: '#9a0e18',
          700: '#730a11',
          800: '#4c070a',
          900: '#260304',
          950: '#130102',
        },
        'bits-deep-purple': {
          50: '#f3e6f7',
          100: '#e0b3e8',
          200: '#cd80d9',
          300: '#ba4dca',
          400: '#a71abb',
          500: '#3B0A45',
          600: '#2f0837',
          700: '#230629',
          800: '#17041b',
          900: '#0b020d',
          950: '#060107',
        },
        'bits-white': '#FFFFFF',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
};
export default config;
